// Code generated by cmd/htmlgen; DO NOT EDIT.

package html

import (
	g "maragu.dev/gomponents"
)

func AllowFullscreen() g.Node {
	return g.Attr("allowfullscreen")
}

func Async() g.Node {
	return g.Attr("async")
}

func AutoFocus() g.Node {
	return g.Attr("autofocus")
}

func AutoPlay() g.Node {
	return g.Attr("autoplay")
}

func Checked() g.Node {
	return g.Attr("checked")
}

func Controls() g.Node {
	return g.Attr("controls")
}

func Default() g.Node {
	return g.Attr("default")
}

func Defer() g.Node {
	return g.Attr("defer")
}

func Disabled() g.Node {
	return g.Attr("disabled")
}

func FormNoValidate() g.Node {
	return g.Attr("formnovalidate")
}

func Inert() g.Node {
	return g.Attr("inert")
}

func Loop() g.Node {
	return g.Attr("loop")
}

func Multiple() g.Node {
	return g.Attr("multiple")
}

func Muted() g.Node {
	return g.Attr("muted")
}

func NoModule() g.Node {
	return g.Attr("nomodule")
}

func NoValidate() g.Node {
	return g.Attr("novalidate")
}

func Open() g.Node {
	return g.Attr("open")
}

func PlaysInline() g.Node {
	return g.Attr("playsinline")
}

func ReadOnly() g.Node {
	return g.Attr("readonly")
}

func Required() g.Node {
	return g.Attr("required")
}

func Reversed() g.Node {
	return g.Attr("reversed")
}

func Selected() g.Node {
	return g.Attr("selected")
}

func Accept(v string) g.Node {
	return g.Attr("accept", v)
}

func AcceptCharset(v string) g.Node {
	return g.Attr("accept-charset", v)
}

func AccessKey(v string) g.Node {
	return g.Attr("accesskey", v)
}

func Action(v string) g.Node {
	return g.Attr("action", v)
}

func Allow(v string) g.Node {
	return g.Attr("allow", v)
}

func Alt(v string) g.Node {
	return g.Attr("alt", v)
}

func As(v string) g.Node {
	return g.Attr("as", v)
}

func AutoCapitalize(v string) g.Node {
	return g.Attr("autocapitalize", v)
}

func AutoComplete(v string) g.Node {
	return g.Attr("autocomplete", v)
}

func Charset(v string) g.Node {
	return g.Attr("charset", v)
}

func CiteAttr(v string) g.Node {
	return g.Attr("cite", v)
}

func Class(v string) g.Node {
	return g.Attr("class", v)
}

func ColSpan(v string) g.Node {
	return g.Attr("colspan", v)
}

func Cols(v string) g.Node {
	return g.Attr("cols", v)
}

func Content(v string) g.Node {
	return g.Attr("content", v)
}

func ContentEditable(v string) g.Node {
	return g.Attr("contenteditable", v)
}

func CrossOrigin(v string) g.Node {
	return g.Attr("crossorigin", v)
}

func DateTime(v string) g.Node {
	return g.Attr("datetime", v)
}

func Dir(v string) g.Node {
	return g.Attr("dir", v)
}

func Download(v string) g.Node {
	return g.Attr("download", v)
}

func Draggable(v string) g.Node {
	return g.Attr("draggable", v)
}

func EncType(v string) g.Node {
	return g.Attr("enctype", v)
}

func EnterKeyHint(v string) g.Node {
	return g.Attr("enterkeyhint", v)
}

func For(v string) g.Node {
	return g.Attr("for", v)
}

func FormAction(v string) g.Node {
	return g.Attr("formaction", v)
}

func FormAttr(v string) g.Node {
	return g.Attr("form", v)
}

func FormEncType(v string) g.Node {
	return g.Attr("formenctype", v)
}

func FormMethod(v string) g.Node {
	return g.Attr("formmethod", v)
}

func FormTarget(v string) g.Node {
	return g.Attr("formtarget", v)
}

func HTTPEquiv(v string) g.Node {
	return g.Attr("http-equiv", v)
}

func Headers(v string) g.Node {
	return g.Attr("headers", v)
}

func Height(v string) g.Node {
	return g.Attr("height", v)
}

func Hidden(v string) g.Node {
	return g.Attr("hidden", v)
}

func High(v string) g.Node {
	return g.Attr("high", v)
}

func Href(v string) g.Node {
	return g.Attr("href", v)
}

func HrefLang(v string) g.Node {
	return g.Attr("hreflang", v)
}

func ID(v string) g.Node {
	return g.Attr("id", v)
}

func InputMode(v string) g.Node {
	return g.Attr("inputmode", v)
}

func Integrity(v string) g.Node {
	return g.Attr("integrity", v)
}

func Is(v string) g.Node {
	return g.Attr("is", v)
}

func LabelAttr(v string) g.Node {
	return g.Attr("label", v)
}

func Lang(v string) g.Node {
	return g.Attr("lang", v)
}

func List(v string) g.Node {
	return g.Attr("list", v)
}

func Loading(v string) g.Node {
	return g.Attr("loading", v)
}

func Low(v string) g.Node {
	return g.Attr("low", v)
}

func Max(v string) g.Node {
	return g.Attr("max", v)
}

func MaxLength(v string) g.Node {
	return g.Attr("maxlength", v)
}

func Media(v string) g.Node {
	return g.Attr("media", v)
}

func Method(v string) g.Node {
	return g.Attr("method", v)
}

func Min(v string) g.Node {
	return g.Attr("min", v)
}

func MinLength(v string) g.Node {
	return g.Attr("minlength", v)
}

func Name(v string) g.Node {
	return g.Attr("name", v)
}

func Nonce(v string) g.Node {
	return g.Attr("nonce", v)
}

func Optimum(v string) g.Node {
	return g.Attr("optimum", v)
}

func Part(v string) g.Node {
	return g.Attr("part", v)
}

func Pattern(v string) g.Node {
	return g.Attr("pattern", v)
}

func Ping(v string) g.Node {
	return g.Attr("ping", v)
}

func Placeholder(v string) g.Node {
	return g.Attr("placeholder", v)
}

func PopoverTarget(v string) g.Node {
	return g.Attr("popovertarget", v)
}

func PopoverTargetAction(v string) g.Node {
	return g.Attr("popovertargetaction", v)
}

func Poster(v string) g.Node {
	return g.Attr("poster", v)
}

func Preload(v string) g.Node {
	return g.Attr("preload", v)
}

func ReferrerPolicy(v string) g.Node {
	return g.Attr("referrerpolicy", v)
}

func Rel(v string) g.Node {
	return g.Attr("rel", v)
}

func Role(v string) g.Node {
	return g.Attr("role", v)
}

func RowSpan(v string) g.Node {
	return g.Attr("rowspan", v)
}

func Rows(v string) g.Node {
	return g.Attr("rows", v)
}

func Sandbox(v string) g.Node {
	return g.Attr("sandbox", v)
}

func Scope(v string) g.Node {
	return g.Attr("scope", v)
}

func Size(v string) g.Node {
	return g.Attr("size", v)
}

func Sizes(v string) g.Node {
	return g.Attr("sizes", v)
}

func SlotAttr(v string) g.Node {
	return g.Attr("slot", v)
}

func SpellCheck(v string) g.Node {
	return g.Attr("spellcheck", v)
}

func Src(v string) g.Node {
	return g.Attr("src", v)
}

func SrcDoc(v string) g.Node {
	return g.Attr("srcdoc", v)
}

func SrcSet(v string) g.Node {
	return g.Attr("srcset", v)
}

func Start(v string) g.Node {
	return g.Attr("start", v)
}

func Step(v string) g.Node {
	return g.Attr("step", v)
}

func Style(v string) g.Node {
	return g.Attr("style", v)
}

func TabIndex(v string) g.Node {
	return g.Attr("tabindex", v)
}

func Target(v string) g.Node {
	return g.Attr("target", v)
}

func Title(v string) g.Node {
	return g.Attr("title", v)
}

func Translate(v string) g.Node {
	return g.Attr("translate", v)
}

func Type(v string) g.Node {
	return g.Attr("type", v)
}

func UseMap(v string) g.Node {
	return g.Attr("usemap", v)
}

func Value(v string) g.Node {
	return g.Attr("value", v)
}

func VirtualKeyboardPolicy(v string) g.Node {
	return g.Attr("virtualkeyboardpolicy", v)
}

func Width(v string) g.Node {
	return g.Attr("width", v)
}

func Wrap(v string) g.Node {
	return g.Attr("wrap", v)
}

func WritingSuggestions(v string) g.Node {
	return g.Attr("writingsuggestions", v)
}

func Popover(v ...string) g.Node {
	return g.Attr("popover", v...)
}

// Aria attributes automatically have their name prefixed with "aria-".
func Aria(name, v string) g.Node {
	return g.Attr("aria-"+name, v)
}

// Data attributes automatically have their name prefixed with "data-".
func Data(name, v string) g.Node {
	return g.Attr("data-"+name, v)
}

// Deprecated: Use [Data] instead.
func DataAttr(name, v string) g.Node {
	return Data(name, v)
}

// Deprecated: Use [Style] instead.
func StyleAttr(v string) g.Node {
	return Style(v)
}

// Deprecated: Use [Title] instead.
func TitleAttr(v string) g.Node {
	return Title(v)
}
