// Code generated by cmd/htmlgen; DO NOT EDIT.

package html

import (
	g "maragu.dev/gomponents"
)

func AllowFullscreen() g.Node {
	return g.Attr("allowfullscreen")
}

func Async() g.Node {
	return g.Attr("async")
}

func AutoFocus() g.Node {
	return g.Attr("autofocus")
}

func AutoPlay() g.Node {
	return g.Attr("autoplay")
}

func Checked() g.Node {
	return g.Attr("checked")
}

func Controls() g.Node {
	return g.Attr("controls")
}

func Default() g.Node {
	return g.Attr("default")
}

func Defer() g.Node {
	return g.Attr("defer")
}

func Disabled() g.Node {
	return g.Attr("disabled")
}

func FormNoValidate() g.Node {
	return g.Attr("formnovalidate")
}

func Inert() g.Node {
	return g.Attr("inert")
}

func IsMap() g.Node {
	return g.Attr("ismap")
}

func ItemScope() g.Node {
	return g.Attr("itemscope")
}

func Loop() g.Node {
	return g.Attr("loop")
}

func Multiple() g.Node {
	return g.Attr("multiple")
}

func Muted() g.Node {
	return g.Attr("muted")
}

func NoModule() g.Node {
	return g.Attr("nomodule")
}

func NoValidate() g.Node {
	return g.Attr("novalidate")
}

func Open() g.Node {
	return g.Attr("open")
}

func PlaysInline() g.Node {
	return g.Attr("playsinline")
}

func ReadOnly() g.Node {
	return g.Attr("readonly")
}

func Required() g.Node {
	return g.Attr("required")
}

func Reversed() g.Node {
	return g.Attr("reversed")
}

func Selected() g.Node {
	return g.Attr("selected")
}

func AbbrAttr(v string) g.Node {
	return g.Attr("abbr", v)
}

func Accept(v string) g.Node {
	return g.Attr("accept", v)
}

func AcceptCharset(v string) g.Node {
	return g.Attr("accept-charset", v)
}

func AccessKey(v string) g.Node {
	return g.Attr("accesskey", v)
}

func Action(v string) g.Node {
	return g.Attr("action", v)
}

func Align(v string) g.Node {
	return g.Attr("align", v)
}

func Allow(v string) g.Node {
	return g.Attr("allow", v)
}

func AllowPaymentRequest(v string) g.Node {
	return g.Attr("allowpaymentrequest", v)
}

func Alpha(v string) g.Node {
	return g.Attr("alpha", v)
}

func Alt(v string) g.Node {
	return g.Attr("alt", v)
}

func Archive(v string) g.Node {
	return g.Attr("archive", v)
}

func As(v string) g.Node {
	return g.Attr("as", v)
}

func AttributionSourceID(v string) g.Node {
	return g.Attr("attributionsourceid", v)
}

func AttributionSrc(v string) g.Node {
	return g.Attr("attributionsrc", v)
}

func AutoCapitalize(v string) g.Node {
	return g.Attr("autocapitalize", v)
}

func AutoComplete(v string) g.Node {
	return g.Attr("autocomplete", v)
}

func AutoCorrect(v string) g.Node {
	return g.Attr("autocorrect", v)
}

func Axis(v string) g.Node {
	return g.Attr("axis", v)
}

func Behavior(v string) g.Node {
	return g.Attr("behavior", v)
}

func Blocking(v string) g.Node {
	return g.Attr("blocking", v)
}

func BrowsingTopics(v string) g.Node {
	return g.Attr("browsingtopics", v)
}

func Capture(v string) g.Node {
	return g.Attr("capture", v)
}

func CellPadding(v string) g.Node {
	return g.Attr("cellpadding", v)
}

func CellSpacing(v string) g.Node {
	return g.Attr("cellspacing", v)
}

func Char(v string) g.Node {
	return g.Attr("char", v)
}

func CharOff(v string) g.Node {
	return g.Attr("charoff", v)
}

func Charset(v string) g.Node {
	return g.Attr("charset", v)
}

func CiteAttr(v string) g.Node {
	return g.Attr("cite", v)
}

func Class(v string) g.Node {
	return g.Attr("class", v)
}

func Classid(v string) g.Node {
	return g.Attr("classid", v)
}

func Clear(v string) g.Node {
	return g.Attr("clear", v)
}

func Closedby(v string) g.Node {
	return g.Attr("closedby", v)
}

func Codebase(v string) g.Node {
	return g.Attr("codebase", v)
}

func Codetype(v string) g.Node {
	return g.Attr("codetype", v)
}

func ColSpan(v string) g.Node {
	return g.Attr("colspan", v)
}

func Colorspace(v string) g.Node {
	return g.Attr("colorspace", v)
}

func Cols(v string) g.Node {
	return g.Attr("cols", v)
}

func Command(v string) g.Node {
	return g.Attr("command", v)
}

func Commandfor(v string) g.Node {
	return g.Attr("commandfor", v)
}

func Compact(v string) g.Node {
	return g.Attr("compact", v)
}

func Content(v string) g.Node {
	return g.Attr("content", v)
}

func ContentEditable(v string) g.Node {
	return g.Attr("contenteditable", v)
}

func ControlsList(v string) g.Node {
	return g.Attr("controlslist", v)
}

func Coords(v string) g.Node {
	return g.Attr("coords", v)
}

func Credentialless(v string) g.Node {
	return g.Attr("credentialless", v)
}

func CrossOrigin(v string) g.Node {
	return g.Attr("crossorigin", v)
}

func Csp(v string) g.Node {
	return g.Attr("csp", v)
}

func DateTime(v string) g.Node {
	return g.Attr("datetime", v)
}

func Declare(v string) g.Node {
	return g.Attr("declare", v)
}

func Decoding(v string) g.Node {
	return g.Attr("decoding", v)
}

func Dir(v string) g.Node {
	return g.Attr("dir", v)
}

func Direction(v string) g.Node {
	return g.Attr("direction", v)
}

func Dirname(v string) g.Node {
	return g.Attr("dirname", v)
}

func DisablePictureInPicture(v string) g.Node {
	return g.Attr("disablepictureinpicture", v)
}

func DisableRemotePlayback(v string) g.Node {
	return g.Attr("disableremoteplayback", v)
}

func Download(v string) g.Node {
	return g.Attr("download", v)
}

func Draggable(v string) g.Node {
	return g.Attr("draggable", v)
}

func EncType(v string) g.Node {
	return g.Attr("enctype", v)
}

func EnterKeyHint(v string) g.Node {
	return g.Attr("enterkeyhint", v)
}

func Face(v string) g.Node {
	return g.Attr("face", v)
}

func FetchPriority(v string) g.Node {
	return g.Attr("fetchpriority", v)
}

func For(v string) g.Node {
	return g.Attr("for", v)
}

func FormAction(v string) g.Node {
	return g.Attr("formaction", v)
}

func FormAttr(v string) g.Node {
	return g.Attr("form", v)
}

func FormEncType(v string) g.Node {
	return g.Attr("formenctype", v)
}

func FormMethod(v string) g.Node {
	return g.Attr("formmethod", v)
}

func FormTarget(v string) g.Node {
	return g.Attr("formtarget", v)
}

func Frame(v string) g.Node {
	return g.Attr("frame", v)
}

func Frameborder(v string) g.Node {
	return g.Attr("frameborder", v)
}

func HTTPEquiv(v string) g.Node {
	return g.Attr("http-equiv", v)
}

func Headers(v string) g.Node {
	return g.Attr("headers", v)
}

func Height(v string) g.Node {
	return g.Attr("height", v)
}

func Hidden(v string) g.Node {
	return g.Attr("hidden", v)
}

func High(v string) g.Node {
	return g.Attr("high", v)
}

func Href(v string) g.Node {
	return g.Attr("href", v)
}

func HrefLang(v string) g.Node {
	return g.Attr("hreflang", v)
}

func HrefTranslate(v string) g.Node {
	return g.Attr("hreftranslate", v)
}

func Hspace(v string) g.Node {
	return g.Attr("hspace", v)
}

func ID(v string) g.Node {
	return g.Attr("id", v)
}

func ImageSizes(v string) g.Node {
	return g.Attr("imagesizes", v)
}

func ImageSrcSet(v string) g.Node {
	return g.Attr("imagesrcset", v)
}

func InputMode(v string) g.Node {
	return g.Attr("inputmode", v)
}

func Integrity(v string) g.Node {
	return g.Attr("integrity", v)
}

func Interestfor(v string) g.Node {
	return g.Attr("interestfor", v)
}

func Is(v string) g.Node {
	return g.Attr("is", v)
}

func ItemID(v string) g.Node {
	return g.Attr("itemid", v)
}

func ItemProp(v string) g.Node {
	return g.Attr("itemprop", v)
}

func ItemRef(v string) g.Node {
	return g.Attr("itemref", v)
}

func ItemType(v string) g.Node {
	return g.Attr("itemtype", v)
}

func Kind(v string) g.Node {
	return g.Attr("kind", v)
}

func LabelAttr(v string) g.Node {
	return g.Attr("label", v)
}

func Lang(v string) g.Node {
	return g.Attr("lang", v)
}

func List(v string) g.Node {
	return g.Attr("list", v)
}

func Loading(v string) g.Node {
	return g.Attr("loading", v)
}

func Longdesc(v string) g.Node {
	return g.Attr("longdesc", v)
}

func Low(v string) g.Node {
	return g.Attr("low", v)
}

func Max(v string) g.Node {
	return g.Attr("max", v)
}

func MaxLength(v string) g.Node {
	return g.Attr("maxlength", v)
}

func Media(v string) g.Node {
	return g.Attr("media", v)
}

func Method(v string) g.Node {
	return g.Attr("method", v)
}

func Min(v string) g.Node {
	return g.Attr("min", v)
}

func MinLength(v string) g.Node {
	return g.Attr("minlength", v)
}

func Name(v string) g.Node {
	return g.Attr("name", v)
}

func Nohref(v string) g.Node {
	return g.Attr("nohref", v)
}

func Nonce(v string) g.Node {
	return g.Attr("nonce", v)
}

func Noresize(v string) g.Node {
	return g.Attr("noresize", v)
}

func Noshade(v string) g.Node {
	return g.Attr("noshade", v)
}

func Optimum(v string) g.Node {
	return g.Attr("optimum", v)
}

func Part(v string) g.Node {
	return g.Attr("part", v)
}

func Pattern(v string) g.Node {
	return g.Attr("pattern", v)
}

func Ping(v string) g.Node {
	return g.Attr("ping", v)
}

func Placeholder(v string) g.Node {
	return g.Attr("placeholder", v)
}

func PopoverTarget(v string) g.Node {
	return g.Attr("popovertarget", v)
}

func PopoverTargetAction(v string) g.Node {
	return g.Attr("popovertargetaction", v)
}

func Poster(v string) g.Node {
	return g.Attr("poster", v)
}

func Preload(v string) g.Node {
	return g.Attr("preload", v)
}

func PrivateToken(v string) g.Node {
	return g.Attr("privateToken", v)
}

func ReferrerPolicy(v string) g.Node {
	return g.Attr("referrerpolicy", v)
}

func Rel(v string) g.Node {
	return g.Attr("rel", v)
}

func Rev(v string) g.Node {
	return g.Attr("rev", v)
}

func Role(v string) g.Node {
	return g.Attr("role", v)
}

func RowSpan(v string) g.Node {
	return g.Attr("rowspan", v)
}

func Rows(v string) g.Node {
	return g.Attr("rows", v)
}

func Rules(v string) g.Node {
	return g.Attr("rules", v)
}

func Sandbox(v string) g.Node {
	return g.Attr("sandbox", v)
}

func Scheme(v string) g.Node {
	return g.Attr("scheme", v)
}

func Scope(v string) g.Node {
	return g.Attr("scope", v)
}

func Scrollamount(v string) g.Node {
	return g.Attr("scrollamount", v)
}

func Scrolldelay(v string) g.Node {
	return g.Attr("scrolldelay", v)
}

func Scrolling(v string) g.Node {
	return g.Attr("scrolling", v)
}

func ShadowRootClonable(v string) g.Node {
	return g.Attr("shadowrootclonable", v)
}

func ShadowRootDelegatesFocus(v string) g.Node {
	return g.Attr("shadowrootdelegatesfocus", v)
}

func ShadowRootMode(v string) g.Node {
	return g.Attr("shadowrootmode", v)
}

func ShadowRootSerializable(v string) g.Node {
	return g.Attr("shadowrootserializable", v)
}

func Shape(v string) g.Node {
	return g.Attr("shape", v)
}

func Size(v string) g.Node {
	return g.Attr("size", v)
}

func Sizes(v string) g.Node {
	return g.Attr("sizes", v)
}

func SlotAttr(v string) g.Node {
	return g.Attr("slot", v)
}

func SpanAttr(v string) g.Node {
	return g.Attr("span", v)
}

func SpellCheck(v string) g.Node {
	return g.Attr("spellcheck", v)
}

func Src(v string) g.Node {
	return g.Attr("src", v)
}

func SrcDoc(v string) g.Node {
	return g.Attr("srcdoc", v)
}

func SrcLang(v string) g.Node {
	return g.Attr("srclang", v)
}

func SrcSet(v string) g.Node {
	return g.Attr("srcset", v)
}

func Standby(v string) g.Node {
	return g.Attr("standby", v)
}

func Start(v string) g.Node {
	return g.Attr("start", v)
}

func Step(v string) g.Node {
	return g.Attr("step", v)
}

func Style(v string) g.Node {
	return g.Attr("style", v)
}

func SummaryAttr(v string) g.Node {
	return g.Attr("summary", v)
}

func TabIndex(v string) g.Node {
	return g.Attr("tabindex", v)
}

func Target(v string) g.Node {
	return g.Attr("target", v)
}

func Title(v string) g.Node {
	return g.Attr("title", v)
}

func Translate(v string) g.Node {
	return g.Attr("translate", v)
}

func Truespeed(v string) g.Node {
	return g.Attr("truespeed", v)
}

func Type(v string) g.Node {
	return g.Attr("type", v)
}

func UseMap(v string) g.Node {
	return g.Attr("usemap", v)
}

func Valign(v string) g.Node {
	return g.Attr("valign", v)
}

func Value(v string) g.Node {
	return g.Attr("value", v)
}

func Valuetype(v string) g.Node {
	return g.Attr("valuetype", v)
}

func Version(v string) g.Node {
	return g.Attr("version", v)
}

func VirtualKeyboardPolicy(v string) g.Node {
	return g.Attr("virtualkeyboardpolicy", v)
}

func Vspace(v string) g.Node {
	return g.Attr("vspace", v)
}

func WebkitDirectory(v string) g.Node {
	return g.Attr("webkitdirectory", v)
}

func Width(v string) g.Node {
	return g.Attr("width", v)
}

func Wrap(v string) g.Node {
	return g.Attr("wrap", v)
}

func WritingSuggestions(v string) g.Node {
	return g.Attr("writingsuggestions", v)
}

func Xmlns(v string) g.Node {
	return g.Attr("xmlns", v)
}

func Popover(v ...string) g.Node {
	return g.Attr("popover", v...)
}
